#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the Monash box, from a fresh clone to a running phase 3 stack.
#
#   ssh student@118.139.133.14
#   cd ~/projects/retina && git pull      # only needed the first time, to get this file
#   bash deploy/bootstrap-wizard.sh
#
# After that it fast-forwards the clone itself, and restores files a build
# rewrote, because auto-deploy.sh skips every run while the clone is dirty.
#
# Safe to re-run: it keeps every secret already in ~/retina/.env, installs a
# stack file only when it differs, and adds a cron line only when it is absent.
#
# deploy/sim/sim.sh runs it with --non-interactive inside a Docker-in-Docker
# replica of this layout, so the whole path is exercised before the box sees it.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# The simulator has no human and no terminal. Overriding the two gates here,
# rather than editing the library above, keeps that library identical across
# every wizard, which is the whole point of it.
NON_INTERACTIVE=0
[[ "${1:-}" == "--non-interactive" || -n "${WIZARD_NON_INTERACTIVE:-}" ]] && NON_INTERACTIVE=1
if [[ "$NON_INTERACTIVE" == "1" ]]; then
  pause()   { note "${1:-continuing} [non-interactive]"; }
  confirm() { note "$1 -> yes [non-interactive]"; return 0; }
fi

REPO="${REPO:-$HOME/projects/retina}"

# This script lives in the clone and pulls that clone, and bash reads a script
# as it executes it: a pull that rewrote this file would feed the shell
# whatever landed at its current offset. Run from a private copy instead, so
# the file being read is one nothing else can touch.
if [[ -z "${WIZARD_DETACHED:-}" ]]; then
  SELF="$(mktemp "${TMPDIR:-/tmp}/retina-wizard.XXXXXX")"
  cp "${BASH_SOURCE[0]}" "$SELF"
  export WIZARD_DETACHED="$SELF"
  exec bash "$SELF" "$@"
fi
# The copy deletes itself, since the process that made it no longer exists.
trap 'rm -f "$WIZARD_DETACHED"' EXIT

STACK="${STACK:-$HOME/retina}"
IMAGE="${IMAGE:-ghcr.io/noobmaster169/retina-api:main}"
PROXY_URL="${PROXY_URL:-http://172.17.0.1:4001}"
HEALTH_URL="${HEALTH_URL:-http://127.0.0.1:8091/health}"
ENV_FILE="$STACK/.env"

fail() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET"; exit 1; }
ok()   { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

banner "Retina on the Monash box"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites"
say "Checking what the deploy needs before anything is changed."

for tool in docker git curl openssl; do
  command -v "$tool" >/dev/null 2>&1 || fail "$tool is not installed"
done
ok "docker, git, curl, openssl"
docker compose version >/dev/null 2>&1 || fail "the docker compose plugin is missing"
ok "docker compose"
docker info >/dev/null 2>&1 || fail "the docker daemon is not reachable from this account"
ok "the docker daemon answers"

[[ -d "$REPO/.git" ]] || fail "no clone at $REPO. Make it first:
     git clone git@github.com-retina:Noobmaster169/retina.git $REPO"

# A dirty clone stops auto-deploy.sh dead, by design: it will not discard
# someone's work. What it cannot tell apart is a file a tool rewrote. Restore
# those, name anything else, and never guess.
DIRTY="$(git -C "$REPO" status --porcelain)"
if [[ -n "$DIRTY" ]]; then
  GENERATED="$(grep -E '(\.egg-info/|__pycache__/|\.pyc$)' <<<"$DIRTY" || true)"
  OTHER="$(grep -vE '(\.egg-info/|__pycache__/|\.pyc$)' <<<"$DIRTY" || true)"
  if [[ -n "$OTHER" ]]; then
    warn "the clone has changes that are not generated files:"
    printf '%s\n' "$OTHER" | sed 's/^/      /'
    fail "deal with those first. auto-deploy.sh will skip every run until the clone is clean."
  fi
  say "the clone is dirty, and only with files a build wrote:"
  printf '%s\n' "$GENERATED" | sed 's/^/      /'
  # Restore, never clean: `git clean` would also delete anything untracked
  # someone left in the clone, and this script must never be why work is lost.
  if confirm "Restore them to what is committed? Nothing untracked is touched."; then
    git -C "$REPO" checkout -- . 2>/dev/null || fail "could not restore the clone"
    ok "clone restored"
  else
    fail "auto-deploy.sh skips every run while the clone is dirty"
  fi
fi

git -C "$REPO" pull --ff-only --quiet origin main 2>/dev/null || warn "could not fast-forward the clone; using what is checked out"
ok "clone at $REPO ($(git -C "$REPO" rev-parse --short HEAD))"

mkdir -p "$STACK" "$STACK/backups"
ok "stack directory $STACK"

# Every pipeline step asks the proxy for structured output, which it serves
# with `claude -p --json-schema`. An older CLI has no such flag.
if command -v claude >/dev/null 2>&1; then
  note "claude $(claude --version 2>/dev/null | head -n1)"
  note "it must be 2.1.274 or newer; stage 6 checks what the proxy actually does"
else
  warn "no claude CLI on PATH for this account: the sonnet aliases will fail"
  SKIPPED+=("install or log in to the claude CLI as this user")
fi

pause "Press Enter to install the stack files."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Stack files"
say "$STACK holds copies of compose.yaml and auto-deploy.sh; cron runs those copies."
say "From here on auto-deploy.sh refreshes both itself, so this is the last time"
say "anyone has to do it by hand."

install_stack_file() {
  local src="$1" dst="$2" mode="$3" name; name="$(basename "$dst")"
  [[ -f "$src" ]] || { warn "missing from the clone: $src"; return 1; }
  if cmp -s "$src" "$dst" 2>/dev/null; then note "$name is already current"; return 0; fi
  [[ -f "$dst" ]] && cp -f "$dst" "$dst.previous"
  # By rename, not in place: cron may be executing the old copy right now.
  install -m "$mode" "$src" "$dst.new" && mv -f "$dst.new" "$dst"
  ok "installed $name"
}

install_stack_file "$REPO/deploy/compose.yaml"   "$STACK/compose.yaml"   644 || fail "could not install compose.yaml"
install_stack_file "$REPO/deploy/auto-deploy.sh" "$STACK/auto-deploy.sh" 755 || fail "could not install auto-deploy.sh"
for runner in run-ngrok.sh run-proxy.sh; do
  [[ -f "$STACK/$runner" ]] || { warn "$STACK/$runner is missing"; SKIPPED+=("copy deploy/$runner to $STACK and set its domain or port"); }
done

pause "Press Enter to check the secrets."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Secrets"
say "$ENV_FILE is the one thing auto-deploy.sh never writes. A value already"
say "there is kept; only a missing one is generated."

# Changing PG_PASSWORD against an initialised volume locks the data away: the
# server keeps the password it was initialised with and the api can no longer
# connect. Refuse rather than generate.
if [[ -z "$(_existing PG_PASSWORD || true)" ]] && docker volume ls -q 2>/dev/null | grep -qx "${STACK##*/}_pgdata"; then
  fail "the Postgres volume ${STACK##*/}_pgdata exists but PG_PASSWORD is not in $ENV_FILE.
     Generating a new one would lock the database away. Recover the old value
     (docker inspect ${STACK##*/}-postgres-1 shows it) and put it in $ENV_FILE first."
fi

ensure_secret() {
  local key="$1" bytes="$2" why="$3" current
  current="$(_existing "$key" || true)"
  if [[ -n "$current" && "$current" != CHANGE_ME* ]]; then note "$key already set, keeping it"; return 0; fi
  say "$why"
  write_env "$key" "$(openssl rand -hex "$bytes")"
}

ensure_secret PG_PASSWORD      32 "Postgres password for the retina user."
ensure_secret API_SHARED_SECRET 32 "Bearer the Vercel frontend sends. Put the same value in the Vercel project."
ensure_secret TEAM_API_KEY     32 "Bearer teammates use to call the API directly."
ensure_secret MINIO_ACCESS_KEY 16 "MinIO root user, and the access key the api and worker sign with."
ensure_secret MINIO_SECRET_KEY 16 "MinIO root password, and the secret key the api and worker sign with."

if confirm "Show the two values Vercel needs (BACKEND_URL and API_SHARED_SECRET)?"; then
  note "API_SHARED_SECRET=$(_existing API_SHARED_SECRET || echo '?')"
  note "BACKEND_URL is the ngrok domain in $STACK/run-ngrok.sh"
fi

pause "Press Enter to bring the stack up."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The stack"
say "postgres, redis, minio, inbox, api, worker. Only the api publishes a port,"
say "on loopback; ngrok is the single door in."

# Always, never "only when absent": the tag on this box may be an image from
# well before the clone's HEAD, and starting that under a new compose file is
# how you get a stack that looks up and serves last month's code. Layer caching
# makes a repeat run quick.
say "building the api image from the clone. The first build takes a few minutes."
docker build -t "$IMAGE" "$REPO/backend" || fail "the api image would not build"
ok "api image built from $(git -C "$REPO" rev-parse --short HEAD)"

cd "$STACK"
docker compose up -d || fail "docker compose up failed; docker compose logs will say why"

say "waiting for the api to migrate and answer /health"
HEALTH_BODY=""
for _ in $(seq 1 60); do
  HEALTH_BODY="$(curl -fsS --max-time 5 "$HEALTH_URL" 2>/dev/null || true)"
  [[ "$HEALTH_BODY" == *'"postgres":"up"'* && "$HEALTH_BODY" == *'"redis":"up"'* ]] && break
  sleep 2
done

if [[ "$HEALTH_BODY" == *'"status":"ok"'* ]]; then
  ok "every dependency reports up"
elif [[ -n "$HEALTH_BODY" ]]; then
  warn "the api answers but something is down: $HEALTH_BODY"
  SKIPPED+=("look at docker compose logs for whatever /health reports down")
else
  warn "no answer from $HEALTH_URL"
  SKIPPED+=("docker compose logs api")
fi

note "published ports (expect only 127.0.0.1:8091):"
docker compose ps --format '  {{.Service}}  {{.Ports}}' 2>/dev/null || true

pause "Press Enter to check the cron lines."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Cron"
say "Deploys are pulled, not pushed: cron is what makes a push to main arrive."

CRON_WANTED=(
  "*/3 * * * * $STACK/auto-deploy.sh"
  "@reboot setsid nohup $STACK/run-proxy.sh >/dev/null 2>&1 </dev/null &"
  "@reboot setsid nohup $STACK/run-ngrok.sh >/dev/null 2>&1 </dev/null &"
  # \% because cron reads a bare % as a newline into the command's stdin.
  "0 3 * * * cd $STACK && docker compose exec -T postgres pg_dump -U retina retina_prod | gzip > backups/retina_\$(date +\\%F).sql.gz"
)

if ! command -v crontab >/dev/null 2>&1; then
  warn "no crontab on this machine; nothing scheduled"
  SKIPPED+=("add the cron lines by hand: ${CRON_WANTED[*]}")
else
  CURRENT_CRON="$(crontab -l 2>/dev/null || true)"
  MISSING=()
  for line in "${CRON_WANTED[@]}"; do
    grep -Fqx -- "$line" <<<"$CURRENT_CRON" || MISSING+=("$line")
  done
  if (( ${#MISSING[@]} == 0 )); then
    ok "all four cron lines are already there"
  else
    say "missing:"
    for line in "${MISSING[@]}"; do note "  $line"; done
    if confirm "Add them? Nothing already in the crontab is touched."; then
      { printf '%s\n' "$CURRENT_CRON"; printf '%s\n' "${MISSING[@]}"; } | grep -v '^$' | crontab - \
        && ok "crontab updated" || warn "crontab refused the update"
    else
      SKIPPED+=("add ${#MISSING[@]} cron line(s) by hand")
    fi
  fi
fi

pause "Press Enter for the day-one checks."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Day one checks"
say "What phase 4 needs to know about this box, in a block to paste into"
say "docs/PROGRESS.md under 'Verified on the box'."

REPORT=()
record() { REPORT+=("$1"); note "$1"; }

if curl -fsS --max-time 5 "$PROXY_URL/healthz" >/dev/null 2>&1; then
  record "proxy at $PROXY_URL: up"
  ALIASES="$(curl -fsS --max-time 10 "$PROXY_URL/v1/models" 2>/dev/null | tr ',' '\n' | grep -o '"id":"[^"]*"' | cut -d'"' -f4 | tr '\n' ' ' || true)"
  record "aliases: ${ALIASES:-<none returned>}"

  if confirm "Send one small call with a JSON schema? It proves structured output really works here."; then
    SCHEMA_ANSWER="$(curl -fsS --max-time 120 "$PROXY_URL/v1/messages" \
      -H 'content-type: application/json' -H 'x-api-key: retina-bootstrap' \
      -d '{"model":"haiku","max_tokens":64,"messages":[{"role":"user","content":"Name one colour."}],"output_config":{"format":{"type":"json_schema","schema":{"type":"object","properties":{"colour":{"type":"string"}},"required":["colour"],"additionalProperties":false}}}}' \
      2>/dev/null || true)"
    if [[ "$SCHEMA_ANSWER" == *'"colour"'* ]]; then
      record "structured output: the provider constrained the answer"
    else
      record "structured output: FAILED. ${SCHEMA_ANSWER:0:200}"
      SKIPPED+=("structured output does not work: check claude --version (needs 2.1.274+) and ~/retina/llm-proxy.log")
    fi
  fi

  if confirm "Fire 8 parallel calls to see whether the proxy queues or refuses them?"; then
    for i in $(seq 1 8); do
      ( curl -fsS --max-time 120 "$PROXY_URL/v1/messages" -H 'content-type: application/json' \
        -H 'x-api-key: retina-bootstrap' \
        -d '{"model":"qwen3:4b","max_tokens":8,"messages":[{"role":"user","content":"hi"}]}' \
        >/dev/null 2>&1 && echo ok ) >> /tmp/retina-parallel.$$ &
    done
    wait
    PARALLEL_OK="$(grep -c ok /tmp/retina-parallel.$$ 2>/dev/null || echo 0)"
    rm -f /tmp/retina-parallel.$$
    record "8 parallel calls: $PARALLEL_OK succeeded"
  fi
else
  warn "no proxy at $PROXY_URL"
  record "proxy at $PROXY_URL: DOWN"
  SKIPPED+=("start the proxy: setsid nohup $STACK/run-proxy.sh >/dev/null 2>&1 </dev/null &")
fi

record "disk free on $HOME: $(df -Ph "$HOME" 2>/dev/null | awk 'NR==2 {print $4}' || echo '?')"
# This box also carries another project's stack, and phase 3 adds Redis, MinIO
# and a second node process to it.
record "memory available: $(free -h 2>/dev/null | awk 'NR==2 {print $7 " of " $2}' || echo '?')"

printf '\n  %spaste this into docs/PROGRESS.md:%s\n\n' "$BOLD" "$RESET"
for line in "${REPORT[@]}"; do printf '  - %s\n' "$line"; done
printf '\n'

finish
